FROM postgres:15

# Установка переменных окружения
ENV POSTGRES_USER=odoo
ENV POSTGRES_PASSWORD=odoo_sportpit_2024
ENV POSTGRES_DB=odoo_sportpit
ENV PGDATA=/var/lib/postgresql/data/pgdata

# Копируем скрипт инициализации если нужен
COPY --chown=postgres:postgres init.sql /docker-entrypoint-initdb.d/ 2>/dev/null || true

# Порт PostgreSQL
EXPOSE 5432

# Запуск PostgreSQL
CMD ["postgres"]
