version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: odoo_postgres
    environment:
      - POSTGRES_DB=odoo_sportpit
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${DB_PASSWORD:-odoo_password}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=ru_RU.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 10s
      retries: 5

  odoo:
    build: .
    container_name: odoo_sportpit
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=odoo
      - DATABASE_PASSWORD=${DB_PASSWORD:-odoo_password}
      - DATABASE_NAME=odoo_sportpit
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin_password}
      - WORKERS=2
      - PORT=8069
    networks:
      - odoo_network
    restart: unless-stopped
    command: odoo -c /etc/odoo/odoo.conf -i base,l10n_ru,mrp,stock,purchase,sale,quality_control,hr,hr_attendance,project,timesheet --load-language=ru_RU

volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local

networks:
  odoo_network:
    driver: bridge