FROM postgres:15-alpine

# Копируем скрипт инициализации
COPY init-db.sh /docker-entrypoint-initdb.d/

# Устанавливаем права
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

# Устанавливаем переменные окружения по умолчанию
ENV POSTGRES_USER=odoo
ENV POSTGRES_PASSWORD=odoo_sportpit_2024
ENV POSTGRES_DB=odoo_sportpit
ENV PGDATA=/var/lib/postgresql/data

EXPOSE 5432
