[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
numReplicas = 1
startCommand = "odoo -c /etc/odoo/railway.conf --without-demo=all"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/web/health"
healthcheckTimeout = 300