[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "odoo -c /etc/odoo/odoo.conf --without-demo=all"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/web/health"
healthcheckTimeout = 300

[[services]]
name = "odoo-sportpit"
type = "web"

[[services]]
name = "postgres"
type = "database"

[environments.production]
name = "production"

[environments.staging]
name = "staging"