[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# NO HEALTHCHECK - Odoo needs time to initialize

[[services]]
name = "odoo-sportpit"
type = "web"
port = 8069