[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "odoo -c /etc/odoo/odoo.conf -i base,l10n_ru,mrp,stock,purchase,sale,quality_control,hr,hr_attendance,project,timesheet --load-language=ru_RU"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/web/health"
healthcheckTimeout = 30

[[services]]
name = "odoo-sportpit"
type = "web"

[[services]]
name = "postgres"
type = "database"

[environments.production]
name = "production"

[environments.staging]
name = "staging"