# Пример файла с секретами - НИКОГДА НЕ КОММИТЬТЕ РЕАЛЬНЫЕ ЗНАЧЕНИЯ!
# Скопируйте этот файл в secrets.yml и заполните реальными данными
# secrets.yml добавлен в .gitignore

production:
  database:
    password: "CHANGE_ME_USE_STRONG_PASSWORD"
    host: "RAILWAY_PROVIDED"
    port: 5432
    name: "odoo_sportpit"
    user: "odoo"
  
  odoo:
    admin_password: "CHANGE_ME_USE_VERY_STRONG_PASSWORD"
    
  integrations:
    mercury:
      api_key: "YOUR_MERCURY_API_KEY"
      api_secret: "YOUR_MERCURY_API_SECRET"
      certificate_path: "/path/to/certificate.pem"
      
    chestny_znak:
      api_key: "YOUR_CHESTNY_ZNAK_API_KEY"
      token: "YOUR_CHESTNY_ZNAK_TOKEN"
      oms_id: "YOUR_OMS_ID"
      
  email:
    smtp_password: "YOUR_SMTP_PASSWORD"
    smtp_user: "your-email@example.com"
    
  railway:
    token: "YOUR_RAILWAY_TOKEN"
    
  github:
    token: "YOUR_GITHUB_TOKEN"
    webhook_secret: "YOUR_WEBHOOK_SECRET"

staging:
  database:
    password: "STAGING_DB_PASSWORD"
    
development:
  database:
    password: "dev_password_only_for_local"