name: Deploy to Railway

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest coverage
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.git,__pycache__,docs,old,build,dist
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.git,__pycache__,docs,old,build,dist
    
    - name: Build Docker image
      run: |
        docker build -t odoo-sportpit:test .
    
    - name: Run Docker container tests
      run: |
        docker run -d --name odoo-test \
          -e DATABASE_HOST=localhost \
          -e DATABASE_PORT=5432 \
          -e DATABASE_USER=odoo \
          -e DATABASE_PASSWORD=odoo \
          -e DATABASE_NAME=test_db \
          -e ADMIN_PASSWORD=admin \
          --network host \
          odoo-sportpit:test
        
        # Wait for Odoo to start
        sleep 30
        
        # Check if Odoo is running
        curl -f http://localhost:8069/web/health || exit 1
        
        docker stop odoo-test
        docker rm odoo-test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Railway CLI
      run: npm install -g @railway/cli
    
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service odoo-sportpit